# Linear Regression Model

In [1]:
#TO PRE-PROCESS DATA\n",
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
from sklearn.linear_model import LinearRegression
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [3]:
#TO READ CSV FILE
data = pd.read_csv("final_data_combined.csv")

In [10]:
data.head(25)

,lat,lon,xco2_level,XCO2PREC (mol CO2/mol dry),Month,Year,DATE,population,primary_fuel,commissioning_year,capacity_mw,city_ascii,capital,city_pop_2022,month,brightness,scan,track,bright_t31,frp
0,-5.0,38.75,0.000414,5.420000e-08,2,2021,2021-02-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,334.72,1.44,1.12,306.50,23.90
1,-5.0,38.75,0.000414,3.570000e-08,3,2021,2021-03-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,330.70,1.15,1.05,306.35,14.65
2,-5.0,38.75,0.000404,5.430000e-08,3,2017,2017-03-01,76316.340,NaN,NaN,NaN,NaN,NaN,NaN,3,326.80,1.00,1.00,304.70,13.90
3,-5.0,38.75,0.000398,2.360000e-08,1,2015,2015-01-01,71487.750,NaN,NaN,NaN,NaN,NaN,NaN,1,325.20,1.10,1.00,304.00,10.10
4,-5.0,38.75,0.000399,1.800000e-08,3,2015,2015-03-01,71487.750,NaN,NaN,NaN,NaN,NaN,NaN,3,329.43,2.04,1.36,301.93,33.81
5,-5.0,38.75,0.000400,3.570000e-08,10,2015,2015-10-01,71487.750,NaN,NaN,NaN,NaN,NaN,NaN,10,330.00,1.10,1.00,305.20,15.40
6,-5.0,38.75,0.000399,2.870000e-08,9,2015,2015-09-01,71487.750,NaN,NaN,NaN,NaN,NaN,NaN,9,322.20,1.10,1.00,302.60,8.70
7,-5.0,38.75,0.000400,2.800000e-08,11,2015,2015-11-01,71487.750,NaN,NaN,NaN,NaN,NaN,NaN,11,323.50,1.10,1.00,300.20,10.40
8,-5.0,38.75,0.000399,2.860000e-08,2,2015,2015-02-01,71487.750,NaN,NaN,NaN,NaN,NaN,NaN,2,329.23,1.29,1.10,305.00,14.78
9,-5.0,38.75,0.000412,3.640000e-08,7,2020,2020-07-01,83089.200,NaN,NaN,NaN,NaN,NaN,NaN,7,312.90,1.00,1.00,296.30,5.90
10,-5.0,38.75,0.000412,2.080000e-08,10,2020,2020-10-01,83089.200,NaN,NaN,NaN,NaN,NaN,NaN,10,330.67,1.23,1.07,308.43,16.80
11,-5.0,38.75,0.000411,6.840000e-08,4,2020,2020-04-01,83089.200,NaN,NaN,NaN,NaN,NaN,NaN,4,307.50,1.00,1.00,292.50,5.90
12,-5.0,38.75,0.000412,2.330000e-08,3,2020,2020-03-01,83089.200,NaN,NaN,NaN,NaN,NaN,NaN,3,312.42,1.05,1.00,293.73,9.80
13,-5.0,38.75,0.000411,3.850000e-08,2,2020,2020-02-01,83089.200,NaN,NaN,NaN,NaN,NaN,NaN,2,315.35,1.85,1.30,294.80,22.55
14,-5.0,38.75,0.000412,1.800000e-08,8,2020,2020-08-01,83089.200,NaN,NaN,NaN,NaN,NaN,NaN,8,319.00,1.20,1.10,299.20,10.85
15,-5.0,38.75,0.000412,2.750000e-08,9,2020,2020-09-01,83089.200,NaN,NaN,NaN,NaN,NaN,NaN,9,325.62,1.24,1.10,304.02,13.00
16,-5.0,38.75,0.000408,1.910000e-08,1,2019,2019-01-01,80747.234,NaN,NaN,NaN,NaN,NaN,NaN,1,330.12,1.18,1.05,302.82,20.48
17,-5.0,38.75,0.000409,2.210000e-08,3,2019,2019-03-01,80747.234,NaN,NaN,NaN,NaN,NaN,NaN,3,324.87,1.80,1.30,300.67,20.40
18,-5.0,38.75,0.000402,4.440000e-08,1,2016,2016-01-01,74151.370,NaN,NaN,NaN,NaN,NaN,NaN,1,322.20,1.10,1.05,300.35,9.50
19,-5.0,38.75,0.000403,4.520000e-08,10,2016,2016-10-01,74151.370,NaN,NaN,NaN,NaN,NaN,NaN,10,327.35,1.10,1.00,309.45,10.10
20,-5.0,38.75,0.000402,4.110000e-08,3,2016,2016-03-01,74151.370,NaN,NaN,NaN,NaN,NaN,NaN,3,332.30,1.47,1.13,298.73,53.50
21,-5.0,38.75,0.000402,4.210000e-08,2,2016,2016-02-01,74151.370,NaN,NaN,NaN,NaN,NaN,NaN,2,328.84,1.40,1.13,304.00,18.56
22,-5.0,38.75,0.000403,2.380000e-08,11,2016,2016-11-01,74151.370,NaN,NaN,NaN,NaN,NaN,NaN,11,333.50,1.00,1.00,310.20,15.90
23,-5.0,38.75,0.000408,2.390000e-08,12,2018,2018-12-01,78396.080,NaN,NaN,NaN,NaN,NaN,NaN,12,317.90,1.50,1.20,297.40,15.20
24,-5.0,38.75,0.000407,4.860000e-08,3,2018,2018-03-01,78396.080,NaN,NaN,NaN,NaN,NaN,NaN,3,340.30,1.05,1.00,300.20,34.35

In [8]:
data.rename(columns = {'XCO2 (mol CO2/mol dry)':'xco2_level'}, inplace = True)

In [12]:
oil_df = data[(data['primary_fuel'] == 'Oil')]
oil_df

,lat,lon,xco2_level,XCO2PREC (mol CO2/mol dry),Month,Year,DATE,population,primary_fuel,commissioning_year,capacity_mw,city_ascii,capital,city_pop_2022,month,brightness,scan,track,bright_t31,frp
67,-4.5,39.375,0.000415,2.940000e-08,11,2021,2021-11-01,NaN,Oil,1999.0,120.0,Mombasa,admin,1200000.0,11,333.64,1.32,1.14,304.64,37.34
68,-4.5,39.375,0.000415,2.940000e-08,11,2021,2021-11-01,NaN,Oil,1999.0,120.0,Kwale,admin,NaN,11,333.64,1.32,1.14,304.64,37.34
69,-4.5,39.375,0.000415,2.940000e-08,11,2021,2021-11-01,NaN,Oil,2001.0,74.5,Mombasa,admin,1200000.0,11,333.64,1.32,1.14,304.64,37.34
70,-4.5,39.375,0.000415,2.940000e-08,11,2021,2021-11-01,NaN,Oil,2001.0,74.5,Kwale,admin,NaN,11,333.64,1.32,1.14,304.64,37.34
71,-4.5,39.375,0.000415,2.940000e-08,11,2021,2021-11-01,NaN,Oil,2011.0,74.0,Mombasa,admin,1200000.0,11,333.64,1.32,1.14,304.64,37.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3386,1.0,36.875,0.000413,5.490000e-08,7,2020,2020-07-01,32629.215,Oil,2012.0,88.0,NaN,NaN,NaN,7,322.30,2.30,1.50,302.00,26.10
3387,1.0,36.875,0.000410,4.590000e-08,3,2019,2019-03-01,31333.754,Oil,2012.0,88.0,NaN,NaN,NaN,3,343.10,1.40,1.20,318.10,41.90
3388,1.0,36.875,0.000402,3.940000e-08,10,2016,2016-10-01,27996.625,Oil,2012.0,88.0,NaN,NaN,NaN,10,304.75,1.10,1.10,286.00,9.10
3389,1.0,36.875,0.000403,5.290000e-08,3,2016,2016-03-01,27996.625,Oil,2012.0,88.0,NaN,NaN,NaN,3,344.45,2.40,1.50,299.65,129.35
3390,1.0,36.875,0.000402,3.520000e-08,9,2016,2016-09-01,27996.625,Oil,2012.0,88.0,NaN,NaN,NaN,9,333.95,1.00,1.00,312.60,15.70

In [13]:
#Create Linear Regression object
reg = linear_model.LinearRegression()

In [14]:
reg.fit(oil_df[['commissioning_year', 'capacity_mw', 'frp' ]], oil_df.xco2_level) #Train the model using the dataset and specify the target variable

LinearRegression()

In [15]:
#Look at the co-efficient
reg.coef_

array([-2.67243027e-08, -3.97761072e-09, -4.82460259e-08])

In [16]:
reg.intercept_

0.0004614574872252408

In [18]:
#Predict
reg.predict([[2022, 150, 40]])

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([0.00040489])

Work out the calculation using the coefficients and the intercept above.

In [19]:
#coefs -2.67243027e-08, -3.97761072e-09, -4.82460259e-08
-2.67243027e-08*2022+-3.97761072e-09*150+-4.82460259e-08*40+0.0004614574872252408

0.0004048944645218408

Try another one

In [20]:
reg.predict([[2018, 120, 38]])

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([0.00040522])